#!/usr/bin/env sh
# Hardware auto-detection for Polybar (portable & safe)

CONFIG_DIR="$HOME/.config/polybar"
SYSTEM_INI="$CONFIG_DIR/system.ini"
LOG_FILE="$CONFIG_DIR/auto-detect.log"

mkdir -p "$CONFIG_DIR"

log() {
    printf '[%s] %s\n' "$(date '+%H:%M:%S')" "$1" >> "$LOG_FILE"
}

# ===============================
# QUICK MODE (SKIP IF RECENT)
# ===============================
if [ "$1" = "--quick" ] && [ -f "$SYSTEM_INI" ]; then
    exit 0
fi

log "=== Starting system detection ==="

# ===============================
# POWER ADAPTER (MAINS)
# ===============================
ADAPTER=""
for ps in /sys/class/power_supply/*; do
    [ -f "$ps/type" ] || continue
    if grep -q "Mains" "$ps/type"; then
        ADAPTER="$(basename "$ps")"
        break
    fi
done
log "Adapter: ${ADAPTER:-none}"

# ===============================
# BATTERY
# ===============================
BATTERY=""
for ps in /sys/class/power_supply/*; do
    [ -f "$ps/type" ] || continue
    if grep -q "Battery" "$ps/type"; then
        BATTERY="$(basename "$ps")"
        break
    fi
done
log "Battery: ${BATTERY:-none}"

# ===============================
# BACKLIGHT
# ===============================
BACKLIGHT=""
if [ -d /sys/class/backlight ]; then
    BACKLIGHT="$(ls /sys/class/backlight 2>/dev/null | head -n1)"
fi
log "Backlight: ${BACKLIGHT:-none}"

# ===============================
# NETWORK (WIRELESS)
# ===============================
WIFI=""
for iface in /sys/class/net/*; do
    [ -d "$iface/wireless" ] || continue
    WIFI="$(basename "$iface")"
    break
done
log "Wireless: ${WIFI:-none}"

# ===============================
# NETWORK (WIRED)
# ===============================
ETH=""
for iface in /sys/class/net/*; do
    name="$(basename "$iface")"

    # skip loopback & virtual
    case "$name" in
        lo|docker*|veth*|br*|vir*|vmnet*) continue ;;
    esac

    [ -d "$iface/wireless" ] && continue

    if [ -f "$iface/type" ] && [ "$(cat "$iface/type")" = "1" ]; then
        ETH="$name"
        break
    fi
done
log "Wired: ${ETH:-none}"

# ===============================
# WRITE system.ini
# ===============================
cat > "$SYSTEM_INI" <<EOF
# Auto-generated by detection.sh
# $(date)

[system]
adapter = $ADAPTER
battery = $BATTERY
backlight = $BACKLIGHT
network_wireless = $WIFI
network_wired = $ETH
EOF

log "Detection finished"

